<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Handle a Rejected Promise with catch</title>
	<link rel="stylesheet" href="">
</head>
<body>
	<script type="module" src="">
			const makeServerRequest = new Promise((resolve, reject) => {
			  // responseFromServer is set to false to represent an unsuccessful response from a server
			  let responseFromServer = false;
			    
			  if(responseFromServer) {
			    resolve("We got the data");
			  } else {  
			    reject("Data not received");
			  }
			});

			makeServerRequest.catch(error => {
			  console.log(error);
			});
	</script>
							<!-- Handle a Rejected Promise with catch
		catch is the method used when your promise has been rejected. It is executed immediately after a promise's reject method is called. Hereâ€™s the syntax:

		myPromise.catch(error => {
		  
		});
		error is the argument passed in to the reject method. -->
							
</body>
</html>